--PRODUCTO COMPRADOS POR EL CLIENT 4
SELECT CLIENTE.IdCliente,  CLIENTE.Nombre, PEDIDO.IdPedido,
LINEAS_PEDIDO.IdProducto, PRODUCTO.Nombre
FROM CLIENTE
INNER JOIN PEDIDO ON PEDIDO.IdCliente = CLIENTE.IdCliente
INNER JOIN LINEAS_PEDIDO ON PEDIDO.IdPedido = LINEAS_PEDIDO.IdPedido
INNER JOIN PRODUCTO ON PRODUCTO.IdProducto = LINEAS_PEDIDO.IdProducto
WHERE  CLIENTE.Nombre='Cliente 4'
order by IdCliente ASC

