----PARTITION BY

SELECT * FROM EMPLEADOS

SELECT NOMBRE, APELLIDO, DEPARTAMENTO,SUM(SUELDO)
OVER(PARTITION BY DEPARTAMENTO) AS "SUMATORIA DE TODOS LOS SUELDOS"
FROM EMPLEADOS;

SELECT DISTINCT NOMBRE, APELLIDO, DEPARTAMENTO, MAX(SUELDO)
OVER (PARTITION BY DEPARTAMENTO) AS "SUELDO MAXIMO POR DEPA"
FROM EMPLEADOS;

SELECT * FROM DBO.Compras_Bikes

SELECT [MARITAL STATUS],[INCOME], [OCCUPATION], MAX([INCOME])
OVER (PARTITION BY [MARITAL STATUS]) AS "AVERAGE DE ENTRADA POR ESTADOS CIVIL"
FROM DBO.Compras_Bikes
ORDER BY [OCCUPATION] ASC;

SELECT [GENDER],[EDUCATION],[OCCUPATION],[CARS], COUNT([CARS])
OVER (PARTITION BY [CARS]) AS "CUENTEO DE TOTAL CARROS"
FROM DBO.Compras_Bikes


SELECT NOMBRE, APELLIDO, AVG(SUELDO) AS "AVERAGE", APODO
FROM EMPLEADOS
GROUP BY NOMBRE, APELLIDO, APODO
HAVING AVG(SUELDO) >= 1 
