--CREAR BASE DE DATOS PARA RESOLVER EL SIGUIENTE PROBLEMA:
--EN UNA TIENDA DE ALQUILER DE VIDEOS SE NECESITA MANEJAR LAS SIGUIENTES ENTIDADES:
--CLIENTES, PELICULAS, ALQUILER, EMPLEADOS

--DEBE SER POSIBLE OBTENER:
--A-PELICULAS DISPONIBLES
--B-PELICULAS ALQUILADAS
--C-CUALES PELICULAS TIENEN UN DETERMINADO CLIENTE EN EL MOMENTO ACTUAL
--D-EMPLEADOS ACTIVOS
--E-PELICULAS POR CATEGORIA
--F-CLIENTES POR TIPO (VIP, REGULAR,ACTIVOS,INACTIVOS,EN LEGAL)
--G- LOS CLIENTES ACTIVOS

--OTRAS NECESIDADES:

--EL SISTEMA NO GUARDA LA FECHA DE CREACION DE UN CLIENTE, PERO LA BASE DE DATOS DEBE 
--DE ALGUNA MANERA MANEJAR LA FECHA EN LA QUE UN CLIENTE FUE CREADO

--UN CLIENTE LUEGO DE CREADO NO PUEDE SER ELIMINADO O BORRADO.

--TANTO EL CLIENTE COMO EL EMPLEADO, EN EL CAMPO ESTADO O ESTATUS SOLO PUEDEN TENER LOS VALORES
--0 Y 1

--SE DEBEN AGREGAR LAS ENTIDADES QUE SEAN NECESARIAS PARA CUMPLIR LOS REQUERIMIENTOS 
--CREAR VISTAS QUE PRESENTEN LAS CONSIGUIENTES CONSULTAS:
--CLIENTES VIP, CON SUS PELICULAS ASIGNADAS
--PELICULAS POR CATEGORIA
--CLIENTES QUE NO TIENEN PELICULAS ASIGNADAS


-----------A TRABAJAR ------

CREATE DATABASE CINEMAJUAN
USE CINEMAJUAN


CREATE TABLE CLIENTES(
ID_CLIENTE INT IDENTITY (100,2),
NOMBRE VARCHAR (25) NOT NULL,
APELLIDO VARCHAR (25) NOT NULL,
EMAIL VARCHAR (20),
TELEFONO VARCHAR (20),
TIPO_CLIENTE VARCHAR(25) NOT NULL,
ESTATUS BIT,
FECHA DATE
CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PELICULAS(
ID_PELICULA INT IDENTITY (01,1),
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
NOMBRE_PELICULA VARCHAR (25),
ANO_FILMACION VARCHAR(5),
STOCK_PELICULAS INT,
CATEGORIA_PELICULA VARCHAR (25),
);

CREATE TABLE ALQUILER (
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
ID_PELICULA INT,
SALA VARCHAR(10),
ENTRADAS_VENDIDAS INT,
CAPACIDAD_PERSONAS INT,
HORA_FUNCION TIME
);



CREATE TABLE EMPLEADO(
NOMBRE_EMPLEADO VARCHAR (25),
APELLIDO VARCHAR (25),
ID_EMPLEADO INT IDENTITY(13,3),
PUESTO VARCHAR(25),
ESTATUS BIT
);

-----------------------INSERTANDO VALORES
SELECT* FROM CLIENTES
SELECT* FROM PELICULAS
SELECT * FROM ALQUILER
SELECT * FROM EMPLEADO

INSERT INTO CLIENTES VALUES ('JUAN','CASTRO','JUAN@GMAIL.COM','8098992589','VIP',1,'1/16/2024')
INSERT INTO CLIENTES VALUES ('PEDRO','FIDEL','PEDRO@GMAIL.COM','8098992589','REGULAR',1,'8/16/2024')
INSERT INTO CLIENTES VALUES ('LUCIANO','CHICO','CHICO@GMAIL.COM','8092258966','ACTIVO',1,'3/16/2024')
INSERT INTO CLIENTES VALUES ('ALTAGRACIO','PEPE','ALTAGRACIO@GMAIL.COM','8098992589','EN LEGAL',1,'2/16/2024')
INSERT INTO CLIENTES VALUES ('BEJAMIN','ALFONSO','ALFONSO@GMAIL.COM','8098992589','ACTIVO',1,'3/16/2024')
INSERT INTO CLIENTES VALUES ('CREAM','DEMETRIO','CREAM@GMAIL.COM','8098992589','EN LEGAL',1,'2/16/2024')
INSERT INTO CLIENTES VALUES ('MAURICIO','AGUSTINO','MAURICIO@GMAIL.COM','8098992589','INACTIVO',1,'2/8/2024')
INSERT INTO CLIENTES VALUES ('LUCAS','LOPE','LUCAS@GMAIL.COM','8092227854','INACTIVO',1,'1/16/2024')
INSERT INTO CLIENTES VALUES ('PENA','AURELIO','PENA@GMAIL.COM','748895625','ACTIVO',1,'2/27/2024')
INSERT INTO CLIENTES VALUES ('TITO','MENDEZ','TOTO@GMAIL.COM','789562369','VIP',1,'1/22/2024')


INSERT INTO PELICULAS VALUES (104,'The Deer King','2004',4,'ROMANCE')

--INSERT INTO PELICULAS VALUES (106,'El peso de un talento descomunal','2000',5,'ACCION')
INSERT INTO PELICULAS VALUES (108,'El triunfo','2016',3,'DUCUMENTAL')
INSERT INTO PELICULAS VALUES (110,'Código Emperador','2016',2,'SUSPENSO')
INSERT INTO PELICULAS VALUES (112,'Viaje al paraíso','2010',1,'ROMANCE')
INSERT INTO PELICULAS VALUES (114,'Las niñas de cristal','2015',2,'DRAMA')
INSERT INTO PELICULAS VALUES (116,'Los ojos de Tammy Faye','2010',1,'ROMANCE')
INSERT INTO PELICULAS VALUES (118,'Sundown','2010',3,'ACCION')
INSERT INTO PELICULAS VALUES (120,'Padre no hay más que uno ','2010',3,'ACCION')
INSERT INTO PELICULAS VALUES (122,'Uncharted','2010',1,'ACCION')

------
SELECT * FROM ALQUILER

INSERT INTO ALQUILER VALUES (104,1,'SALA 1',150,200,'7:30')
INSERT INTO ALQUILER VALUES (106,3,'SALA 2',50,75,'5:30')
INSERT INTO ALQUILER VALUES (108,4,'SALA 3',80,100,'7:30')
INSERT INTO ALQUILER VALUES (110,6,'SALA 4',75,100,'7:45')
INSERT INTO ALQUILER VALUES (112,7,'SALA 5',50,75,'8:30')
INSERT INTO ALQUILER VALUES (114,8,'SALA 1',125,200,'9:30')
INSERT INTO ALQUILER VALUES (116,9,'SALA 2',66,75,'8:30')
INSERT INTO ALQUILER VALUES (118,10,'SALA 3',87,100,'9:30')
INSERT INTO ALQUILER VALUES (120,11,'SALA 4',89,100,'10:30')

--INSERT INTO ALQUILER VALUES (122,4,'SALA 3',80,100,'7:30')

SELECT * FROM EMPLEADO

INSERT INTO EMPLEADO VALUES ('JUANA','MARGARITA','GERENTE',1 )
INSERT INTO EMPLEADO VALUES ('PEDRO','ANTONIO','ADM',0 )
INSERT INTO EMPLEADO VALUES ('LUCIA','TENESI','CONSERJE',0 )
INSERT INTO EMPLEADO VALUES ('LUCAS','CREAM','CAJERO',1 )
INSERT INTO EMPLEADO VALUES ('MARGOT','MERCEDES','CAJERO',1 )
INSERT INTO EMPLEADO VALUES ('IMBERT','BARRERAS JR','SEGURIDAD',1 )


-------REALIZANDO LA PRACTICA

---PELICULAS DISPONIBLES---------------------------------------------------------------------------------
SELECT P.ID_PELICULA, NOMBRE_PELICULA, SALA, (CAPACIDAD_PERSONAS-ENTRADAS_VENDIDAS) AS 'ASIENTOS_DISPONIBLES EN SALA',
CASE 
	WHEN ENTRADAS_VENDIDAS <200 THEN 'PELICULA DISPONIBLE'
	WHEN ENTRADAS_VENDIDAS <75 THEN 'PELICULA DISPONIBLE'
	WHEN ENTRADAS_VENDIDAS <100 THEN 'PELICULA DISPONIBLE'
	WHEN ENTRADAS_VENDIDAS <100 THEN 'PELICULA DISPONIBLE'
	WHEN ENTRADAS_VENDIDAS <75 THEN 'PELICULA DISPONIBLE'
ELSE 'LA PELICULA NO ESTA DISPONIBLE'
END AS DISPONIBILIDAD
FROM PELICULAS P
JOIN ALQUILER A ON P.ID_PELICULA = A.ID_PELICULA


---PELICULAS ALQUILADAS
SELECT P.ID_PELICULA,P.ID_CLIENTE,NOMBRE_PELICULA,SALA
FROM PELICULAS P
JOIN ALQUILER A ON P.ID_PELICULA = A.ID_PELICULA
ORDER BY SALA

---PELICULAS CON UN DETERMINADO CLIENTE EN MOMENTO ACTUAL
SELECT C.NOMBRE, P.NOMBRE_PELICULA
FROM CLIENTES C
JOIN PELICULAS P ON C.ID_CLIENTE = P.ID_CLIENTE

---EMPLEADOS ACTIVOS
SELECT NOMBRE_EMPLEADO, PUESTO, ESTATUS,
CASE 
	WHEN ESTATUS = 1 THEN 'ACTIVO'
	ELSE 'INACTIVO'
END AS ESTATUS
FROM EMPLEADO;

--E-PELICULAS POR CATEGORIA
SELECT * FROM PELICULAS

SELECT NOMBRE_PELICULA, ANO_FILMACION, CATEGORIA_PELICULA
FROM PELICULAS

--F-CLIENTES POR TIPO (VIP, REGULAR,ACTIVOS,INACTIVOS,EN LEGAL)
SELECT * FROM CLIENTES

SELECT NOMBRE, APELLIDO, TIPO_CLIENTE,
CASE
	WHEN TIPO_CLIENTE = 'VIP' THEN 'FILAS DE ASIENTOS 1A'
	WHEN TIPO_CLIENTE = 'REGULAR' THEN 'FILAS DE ASIENTOS 2B'
	WHEN TIPO_CLIENTE = 'ACTIVO' THEN 'CLIENTE ESTA CONSUMIENDO'
	WHEN TIPO_CLIENTE = 'EN LEGAL' THEN 'CLIENTE TIENE DEUDA'
	WHEN TIPO_CLIENTE = 'INACTIVO' THEN 'CLIENTE MULTADO POR NO PAGAR'
ELSE 'FAVOR PASAR A ADMINISTRACION'
END AS RESULTADO_TIPO_CLIENTE
FROM CLIENTES;

--G- LOS CLIENTES ACTIVOS
SELECT NOMBRE, APELLIDO, TIPO_CLIENTE,
CASE
	WHEN TIPO_CLIENTE = 'VIP' THEN 'FILAS DE ASIENTOS 1A'
	WHEN TIPO_CLIENTE = 'REGULAR' THEN 'FILAS DE ASIENTOS 2B'
	WHEN TIPO_CLIENTE = 'ACTIVO' THEN 'CLIENTE ESTA CONSUMIENDO'
	WHEN TIPO_CLIENTE = 'EN LEGAL' THEN 'CLIENTE TIENE DEUDA'
	WHEN TIPO_CLIENTE = 'INACTIVO' THEN 'CLIENTE MULTADO POR NO PAGAR'
ELSE 'FAVOR PASAR A ADMINISTRACION'
END AS RESULTADO_TIPO_CLIENTE
FROM CLIENTES

WHERE TIPO_CLIENTE = 'ACTIVO';

--EL SISTEMA NO GUARDA LA FECHA DE CREACION DE UN CLIENTE, PERO LA BASE DE DATOS DEBE 
--DE ALGUNA MANERA MANEJAR LA FECHA EN LA QUE UN CLIENTE FUE CREADO

CREATE TABLE CONTROL (
NOMBRE_USUARIO VARCHAR(25),
ACCION VARCHAR(25),
FEHA DATE
);


CREATE TRIGGER TRI_CREACION
ON CLIENTES
AFTER INSERT
AS 
	BEGIN
	DECLARE @NOMBRE_USUARIO VARCHAR(25);
	SET @NOMBRE_USUARIO = SUSER_NAME();
	INSERT INTO CONTROL VALUES (@NOMBRE_USUARIO,'CREAR_CLIENTE',GETDATE())
	END;

INSERT INTO CLIENTES VALUES ('JUAN','ERNESTO','DELAWERE@GMAIL.COM','8097789966','INACTIVO',0,'1/23/2024')

SELECT* FROM CONTROL

--UN CLIENTE LUEGO DE CREADO NO PUEDE SER ELIMINADO O BORRADO.

CREATE OR ALTER TRIGGER TRI_DELETE
ON CLIENTES
INSTEAD OF DELETE
AS 
	BEGIN
		RAISERROR('USTED NO PUEDE ELIMINAR EL CLIENTE',16,1)
		RETURN
	END;

DELETE FROM CLIENTES WHERE ID_CLIENTE = 120


--TANTO EL CLIENTE COMO EL EMPLEADO, EN EL CAMPO ESTADO O ESTATUS SOLO PUEDEN TENER LOS VALORES
--0 Y 1
SELECT * FROM CLIENTES
SELECT * FROM EMPLEADO



--CREAR VISTAS QUE PRESENTEN LAS CONSIGUIENTES CONSULTAS:
--CLIENTES VIP, CON SUS PELICULAS ASIGNADAS
SELECT TIPO_CLIENTE,NOMBRE_PELICULA
FROM PELICULAS P
JOIN CLIENTES C ON C.ID_CLIENTE = P.ID_CLIENTE
WHERE TIPO_CLIENTE = 'VIP';

--PELICULAS POR CATEGORIA
SELECT NOMBRE_PELICULA, CATEGORIA_PELICULA
FROM PELICULAS


