----PROBANDO LOS CONOCIMIENTOS A VER COMO ESTOY PARA UNA ENTREVISTA.
--LOS PUNTOS A TRATAR SON:
--1.WHERE
--2.GROUP BY
--3.JOIN
--4.HAVING
--5.IF-ELSE
--6.CASE
--7.CURSORES
--8.TRIGGERS
--9.PARTITION BY
--10.WITH AS (CTE)
--11.SUB-CONSULTAS
--12.STORE PROCEDURE
--13.ROW NUMBER
--14.CURSORES

--UTILIZANDO LA BASE DE DATOS PRACTICANDO, CREAR RELACION

SELECT FIRST_NAME, LAST_NAME, SALARY 
FROM EMPLOYEES 
WHERE SALARY >4800;

---MODIFICANDO EL SALARIO PARA LOS EMPLEADOS DE ACUERDO AL MANAGER_ID
SELECT * FROM EMPLOYEES;

UPDATE EMPLOYEES
SET SALARY = SALARY + 1121
WHERE MANAGER_ID = 100;

UPDATE EMPLOYEES 
SET SALARY  = SALARY + 2025
WHERE MANAGER_ID = 101;

UPDATE EMPLOYEES
SET SALARY = SALARY + 4050
WHERE MANAGER_ID = 102;

UPDATE EMPLOYEES
SET SALARY = SALARY + 16200
WHERE MANAGER_ID = 103;

--1.WHERE
SELECT E.FIRST_NAME, 
		E.LAST_NAME,
		E.EMAIL,
		E.HIRE_DATE,
		CO.COUNTRY_NAME
FROM EMPLOYEES E
JOIN DEPARTMENT DE ON E.DEPARTMENT_ID = DE.DEPARTMENT_ID
JOIN LOCATIONS LO ON DE.LOCATION_ID = LO.LOCATION_ID
JOIN COUNTRY CO ON LO.COUNTRY_ID  = CO.COUNTRY_ID
JOIN REGION RE ON CO.REGION_ID = RE.REGION_ID
WHERE COUNTRY_NAME = 'CANADA';


---MODIFICANDO EL NOMBRE DE LA COLUMNA LIOCATON_ID POR LOCATION_ID
EXEC sp_rename 'DEPARTMENT.LIOCATION_ID', 'LOCATION_ID', 'COLUMN';

--2.GROUP BY (SE AGRUPA POR LAS COLUMNAS QUE NO TIENEN FUNCION AGREGADAS COMO: COUNT, SUM, MIN, AVG)
SELECT COUNT (DISTINCT FIRST_NAME) AS 'CANTIDAD DE NOMBRES', LAST_NAME, PHONE_NUMBER, SUM(SALARY) AS 'SUMA DE SALARIO'
FROM EMPLOYEES
GROUP BY FIRST_NAME, LAST_NAME, PHONE_NUMBER

--2.GROUP BY CON JOIN ADICIONADO

SELECT E.FIRST_NAME, 
		E.LAST_NAME,
		CO.COUNTRY_NAME,
		SUM(SALARY)AS 'SUMA SALARIO'
FROM EMPLOYEES E
JOIN DEPARTMENT DE ON E.DEPARTMENT_ID = DE.DEPARTMENT_ID
JOIN LOCATIONS LO ON DE.LOCATION_ID = LO.LOCATION_ID
JOIN COUNTRY CO ON LO.COUNTRY_ID  = CO.COUNTRY_ID
JOIN REGION RE ON CO.REGION_ID = RE.REGION_ID
WHERE COUNTRY_NAME = 'CANADA'
GROUP BY FIRST_NAME, LAST_NAME, COUNTRY_NAME;

--3.JOIN (NOS PERMITE ENLAZAR VARIAS TABLAS PARA PODER OBTENER REGISTROS)

SELECT	E.FIRST_NAME, 
		E.LAST_NAME,
		E.JOB_ID,
		L.CITY,
		L.STATE_PROVINCE
FROM EMPLOYEES E
		JOIN DEPARTMENT DE ON E.DEPARTMENT_ID = DE.DEPARTMENT_ID
		JOIN LOCATIONS L ON DE.LOCATION_ID = L.LOCATION_ID
WHERE CITY = 'SEATTLE' AND JOB_ID = 5;		
		
--4.HAVING ()
SELECT FIRST_NAME, LAST_NAME, PHONE_NUMBER, AVG(SALARY) AS 'AVERAGE DE SALARIO', COUNT(DEPARTMENT_ID) AS 'CONTEO DE DEPARTAMENTO'
FROM EMPLOYEES
WHERE LAST_NAME = 'lorentz'
GROUP BY FIRST_NAME, LAST_NAME, PHONE_NUMBER
HAVING AVG(SALARY) > 5000;

---REALIZANDO OTRO HAVING

SELECT	E.LAST_NAME AS APELLIDO, 
		E.HIRE_DATE AS FECHA_CONTRATACION, 
		E.MANAGER_ID AS ID_SUPERVISOR,
		MIN(SALARY) AS SALARIO_MINIMO,
		JH.START_DATE AS FECHA_INICIO
FROM EMPLOYEES E
JOIN JOB_HISTORY JH ON JH.EMPLOYEE_ID = E.EMPLOYEE_ID
WHERE LAST_NAME = UPPER('KOCHAR')
GROUP BY E.LAST_NAME, E.HIRE_DATE, E.MANAGER_ID, JH.START_DATE
HAVING MIN(SALARY) =8163;


--IF -- ELSE (EXIST)

IF EXISTS (SELECT * FROM EMPLOYEES WHERE MANAGER_ID =100)
	(SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES
	  WHERE MANAGER_ID = 100)
	  
ELSE
	SELECT 'NO SE PUDO REALIZAR LA CONSULTA' AS MENSAJE;

---REALIZANDO OTRO NUEVO IF EXISTS
IF EXISTS (SELECT * FROM DEPARTMENT WHERE DEPARTMENT_NAME LIKE '%AD%' )
	(SELECT DEPARTMENT_ID FROM DEPARTMENT WHERE DEPARTMENT_NAME LIKE '%AD%')
ELSE 
	SELECT 'NO HAY REGISTROS PARECIDOS' AS MENSAJE;

--6.CASE
SELECT * FROM EMPLOYEES

SELECT FIRST_NAME,
		LAST_NAME,
		MANAGER_ID,
	CASE
			WHEN MANAGER_ID = 100 THEN 'SUP. JUAN'
			WHEN MANAGER_ID = 101 THEN 'SUP. JOSE'
			WHEN MANAGER_ID = 102 THEN 'SUP. PEDRO SANTANA'
			WHEN MANAGER_ID = 103 THEN 'SUP.KATHERINE'

		ELSE 'NO HAY NINGUN AGENTE BAJO SUPERVISION'
	END AS 'SUPERVISORES ASIGNADOS A EMPLEADOS'

FROM EMPLOYEES
ORDER BY MANAGER_ID ASC;

----COMBINANDO CASES CON JOIN

SELECT	E.FIRST_NAME, 
		E.LAST_NAME,
		DE.DEPARTMENT_NAME, 
		E.SALARY,
	CASE 
		WHEN SALARY BETWEEN 00000 AND 10000 THEN 'SALARIO BAJO'
		WHEN SALARY BETWEEN 10001 AND 20000 THEN 'SALARIO INTERMEDIO'
		WHEN SALARY BETWEEN 20001 AND 30000 THEN 'SALARIO ALTO'
	ELSE 'SALARIO NO CLASIFICADO'
END AS 'CLASIFICACION DE SALARIO'
FROM EMPLOYEES E
JOIN DEPARTMENT DE ON E.DEPARTMENT_ID = DE.DEPARTMENT_ID
ORDER BY SALARY ASC, DEPARTMENT_NAME DESC;

--7.CURSORES
--8.TRIGGERS
--9.PARTITION BY
--10.WITH AS (CTE)
--11.SUB-CONSULTAS
--12.STORE PROCEDURE
--13.ROW NUMBER
--14.CURSORES


