--DECLARANDO VARIABLES
DECLARE @HOMEOWNER VARCHAR(25);

--DECLARANDO EL CURSOR
DECLARE 
	APODCURSOR CURSOR FOR SELECT APODO FROM EMPLEADOS

OPEN APODCURSOR
FETCH NEXT FROM APODCURSOR INTO @HOMEOWNER
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'EL APODO ES ' + ' ' +  @HOMEOWNER
	FETCH NEXT FROM APODCURSOR INTO @HOMEOWNER
	END
CLOSE APODCURSOR
DEALLOCATE APODCURSOR

--------**********REALIZANDO OTRO CURSOR PARA PROBAR HABILIDAD*******************************************


--DECLARANDO LA VARIABLE DONDE SE ALMACENARAN LOS VALORES
DECLARE @BONIFICACION NUMERIC (10,2);

--DECLARANDO EL CURSOR Y SELECCIONANDO LA TABLA
DECLARE CUR_BONOS CURSOR FOR SELECT BONOS FROM NOMINA

--ABRIENDO EL CURSOR
OPEN CUR_BONOS
FETCH NEXT FROM CUR_BONOS INTO @BONIFICACION
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT  @BONIFICACION
	FETCH NEXT FROM CUR_BONOS INTO  @BONIFICACION
	END
--CERRANDO EL CURSOR 
CLOSE CUR_BONOS
DEALLOCATE CUR_BONOS

----CURSORES TIPO TABLA--- VERIFICAR CURSOR
DECLARE
	@ARS   DECIMAL (10,2),
	@AFP   DECIMAL (10,2),
	@ISR   DECIMAL (10,2);

DECLARE CUR_DEDUCCIONES CURSOR LOCAL STATIC READ_ONLY 
FOR SELECT ARS, AFP, ISR FROM NOMINA;

OPEN CUR_DEDUCCIONES;
FETCH NEXT FROM CUR_DEDUCCIONES INTO @ARS, @AFP, @ISR
WHILE @@FETCH_STATUS = 0
	BEGIN

	PRINT STR(@ARS) + STR(@AFP) + STR(@ISR);
	FETCH NEXT FROM CUR_DEDUCCIONES INTO @ARS, @AFP, @ISR;
END;
CLOSE CUR_DEDUCCIONES;
DEALLOCATE CUR_DEDUCCIONES;






