USE DiplomadoSQL

--PRACTICANDO CON IF--EL

IF EXISTS (SELECT * FROM EMPLEADOS WHERE APELLIDO = 'LOPOLDO')
	(SELECT NOMBRE, SUELDO  FROM EMPLEADOS WHERE APELLIDO = 'LOPOLDO' )
ELSE 
	SELECT 'NO HAY REGISTROS' AS RESULTADO

---PRACTICANDO IF--ELSE
SELECT * FROM EMPLEADOS

IF EXISTS( SELECT * FROM EMPLEADOS WHERE SUELDO >=7500 )
	(SELECT CODIGO_EMPLEADO, NOMBRE, APODO FROM EMPLEADOS WHERE SUELDO >=75000)
ELSE
	SELECT 'EMPLEADOS MISERABLES' AS RESULTADO

----CREACION DE TABLAS TEMPORALES
CREATE TABLE #MERIENDA(
NOMBRE_MERIENDA VARCHAR (25),
CALORIAS VARCHAR(10),
DATOS_NUTRICION NUMERIC (10,2)
)

INSERT INTO #MERIENDA VALUES ('JUGO_NARANJA', '25KGR',25 )

SELECT * FROM #MERIENDA
DROP TABLE #MERIENDA

---REALIZANDO OTRA TABLA TEMP
CREATE TABLE #NEW_QUERY(
NOMBRE VARCHAR (25),
APELLIDO CHAR (30),
APODO CHAR (25),
SUELDO INT
)

INSERT INTO #NEW_QUERY VALUES ('JUANA','PEPE','EL LOCO',25000)
SELECT * FROM #NEW_QUERY

DROP TABLE #NEW_QUERY
-----**************************************************************
--CLAUSULA HAVING + JOIN

SELECT * FROM EMPLEADOS
SELECT * FROM NOMINA

SELECT NOMBRE, APELLIDO, AVG(SUELDO),APODO, ARS
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY NOMBRE , APELLIDO, APODO, ARS
HAVING AVG(SUELDO)>7500
ORDER BY APODO

----REALIZANDO OTRA PRUEBA PARA VER HABILIDAD
SELECT NOMBRE, APELLIDO, COUNT(AFP), AVG(ARS), SUM(ISR)
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY NOMBRE, APELLIDO
HAVING COUNT(AFP)=789.66

----CREANDO CURSOR PARA PROBAR HABILIDAD

DECLARE @BONIFICACION NUMERIC (10,2);
DECLARE CUR_BUNUS CURSOR FOR SELECT BONOS FROM NOMINA

OPEN CUR_BUNUS
FETCH NEXT FROM CUR_BUNUS INTO @BONIFICACION
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @BONIFICACION
	FETCH NEXT FROM CUR_BUNUS INTO @BONIFICACION
END
	CLOSE CUR_BUNUS
	DEALLOCATE CUR_BUNUS

-----CREANDO UN NUEVO CURSOR
DECLARE @NAME VARCHAR (25);
DECLARE CUR_NAME CURSOR FOR SELECT NOMBRE FROM EMPLEADOS

OPEN CUR_NAME
FETCH NEXT FROM  CUR_NAME INTO @NAME
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NAME
	FETCH NEXT FROM  CUR_NAME INTO @NAME
END;
	CLOSE CUR_NAME
	DEALLOCATE CUR_BUNUS
-----OTRO

DECLARE @BULTICO VARCHAR(25);

DECLARE CUR_PRUEBA CURSOR FOR SELECT SALARIO FROM EMPLEADOS

OPEN CUR_PRUEBA
FETCH NEXT FROM CUR_PRUEBA INTO @BULTICO
WHILE @@FETCH_STATUS = 0
	BEGIN
	PRINT CUR_PRUEBA
	FETCH NEXT FROM CUR_PRUEBA
	END
CLOSE CUR_PRUEBA
DEALLOCATE CUR_PRUEBA
----------------------------------
DECLARE @OFTAFRED VARCHAR (25)
DECLARE CUR_OFTA CURSOR FOR SELECT APELLIDO FROM EMPLEADOS

OPEN CUR_OFTA 
FETCH NEXT FROM CUR_OFTA INTO @OFTAFRED
WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT CUR_OFTA
		FETCH NEXT FROM CUR_OFTA
	END
CLOSE CUR_PRUEBA
DEALLOCATE CUR_PRUEBA
---------------------------------SIGUIENTE TEMA A PRACTICAR---------
CREATE OR ALTER PROCEDURE PROC_INSERT12
@CODIGO_EMPLEADO INT,
@NOMBRE VARCHAR (25),
@APELLIDO VARCHAR(25),
@SUELDO INT,
@APODO VARCHAR(25),
@DEPARTAMENTO VARCHAR(25)
AS
	BEGIN
		INSERT INTO EMPLEADOS VALUES(@CODIGO_EMPLEADO,@NOMBRE,@APELLIDO,@SUELDO,@APODO,@DEPARTAMENTO)
	END

EXEC PROC_INSERT12 1033,'TINI','ORTIZ',83000,'BILLINGS','OFTALMOLOGIA'
-------------------------------------------------------------------
SELECT * FROM EMPLEADOS
SELECT * FROM Nomina
------------------------------------------------------------------

CREATE OR ALTER PROCEDURE PRO_INSERTAR_EN_NOMINA
@CODIGO INT,
@BONOS NUMERIC (10,2),
@AFP DECIMAL (10,2),
@ARS DECIMAL (10,2),
@ISR DECIMAL(10,2),
@SUBSIDIO DECIMAL (10,2)

AS 
	BEGIN
		INSERT INTO NOMINA VALUES (@CODIGO,@BONOS,@AFP,@ARS,@ISR,@SUBSIDIO)
	END;

EXEC PRO_INSERTAR_EN_NOMINA 1033,1000,450.25,355.23,855.33,478.33
--------------------------------DONE---------------------------------  

SELECT * FROM EMPLEADOS
SELECT * FROM NOMINA

SELECT NOMBRE, APELLIDO, AFP, BONOS
FROM EMPLEADOS E
RIGHT JOIN NOMINA N ON E.Codigo_Empleado = N.Codigo

SELECT NOMBRE, APELLIDO, AFP, BONOS
FROM EMPLEADOS E
LEFT  JOIN NOMINA N ON E.Codigo_Empleado = N.Codigo

SELECT NOMBRE, APELLIDO, AFP, BONOS
FROM EMPLEADOS E
INNER JOIN NOMINA N ON E.Codigo_Empleado = N.Codigo

SELECT NOMBRE, APELLIDO, AFP, BONOS
FROM EMPLEADOS E
FULL OUTER JOIN NOMINA N ON E.Codigo_Empleado = N.Codigo










