---PRACTICANDO ENTREVISTA INGENIERO DATOS 2

--JOIN
SELECT E.CODIGO_EMPLEADO, E.APELLIDO,SUELDO, N.SUBSIDIO
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
WHERE SUBSIDIO <= 148;

--CLAUSULA GROUP BY
SELECT NOMBRE, APELLIDO, APODO, MAX(BONOS) AS MAX_BONOS
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY NOMBRE, APELLIDO, APODO
HAVING MAX(BONOS) >=100;

DELETE FROM EMPLEADOS
WHERE CODIGO_EMPLEADO = 1030;


--CLAUSULA WHERE
SELECT NOMBRE, SUELDO, DEPARTAMENTO
FROM EMPLEADOS
WHERE NOMBRE != 'JUAN SORRILLA';

SELECT NOMBRE, APELLIDO, SUELDO, AVG(BONOS) AS AVG_BONOS
FROM EMPLEADOS E
JOIN NOMINA N ON E.	CODIGO_EMPLEADO = N. CODIGO
WHERE APELLIDO = 'Lopoldo'
GROUP BY NOMBRE, APELLIDO, SUELDO
HAVING AVG(BONOS) > 25;

--CLAUSULA HAVING
SELECT NOMBRE, APELLIDO, AVG(SUELDO) AS AVG_SUELDO, MAX(AFP) AS MAX_AFP
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY NOMBRE, APELLIDO
HAVING AVG(SUELDO)> =75000 AND MAX(AFP)>=741.25;

SELECT APELLIDO, SUELDO, COUNT(SUELDO) AS CONTEO_DE_SUELDO
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY APELLIDO, SUELDO
HAVING COUNT(SUELDO) > 1;


--IF - ELSE
IF EXISTS (SELECT * FROM EMPLEADOS WHERE SUELDO = 75000)
(SELECT NOMBRE, APELLIDO, APODO FROM EMPLEADOS WHERE SUELDO = 75000)

ELSE
SELECT 'NO HAY REGISTROS' AS Resultado


--CASE WITH JOIN
SELECT NOMBRE, APELLIDO, AFP, ISR,	
CASE
	WHEN APELLIDO = 'Lopoldo' THEN 'EL ABUSADOR'
	WHEN APELLIDO = 'Diaz' AND AFP = 789.25 THEN 'EL AMANECER'
	ELSE APODO
END AS RESULTADO

FROM EMPLEADOS E
JOIN NOMINA N ON CODIGO_EMPLEADO = CODIGO

--CASE WITH JOIN-2--
SELECT NOMBRE, APELLIDO, DEPARTAMENTO, BONOS, SUBSIDIO,
	CASE 
		WHEN NOMBRE = 'JUAN SORILLA' AND APELLIDO = 'Lopoldo' THEN 'EL MEJOR'
		WHEN NOMBRE = 'JUAN LA LUZ'  AND APELLIDO = 'PEREZ' THEN 'EL CATA'
		WHEN BONOS = 800 AND SUBSIDIO = 100 THEN 'BUEN EMPLEADO'
		WHEN BONOS = 900 AND SUBSIDIO = 125 THEN 'GRAN GERENTE'
ELSE 'NO HAY EMPLEADOS' 
	END AS COMBINACION
FROM EMPLEADOS E
JOIN NOMINA N ON CODIGO_EMPLEADO = CODIGO 
ORDER BY APELLIDO ASC;


--FUNCIONES ESCALARES
--CURSOR
DECLARE
@SUELDO INT

DECLARE CUR_NOM_APELL_SUEL CURSOR FOR SELECT SUELDO FROM EMPLEADOS
OPEN CUR_NOM_APELL_SUEL
FETCH NEXT FROM CUR_NOM_APELL_SUEL INTO @SUELDO
WHILE @@FETCH_STATUS = 0

	BEGIN
	PRINT @SUELDO
	FETCH NEXT FROM CUR_NOM_APELL_SUEL INTO @SUELDO
	END

DEALLOCATE CUR_NOM_APELL_SUEL
CLOSE CUR_NOM_APELL_SUEL
------CURSOR PARA  REALIZAR PRACTICA ALONE
DECLARE @NOMBRE VARCHAR (25)
DECLARE CUR_NOMBRE CURSOR FOR SELECT NOMBRE FROM EMPLEADOS

OPEN CUR_NOMBRE
FETCH NEXT FROM CUR_NOMBRE INTO @NOMBRE
WHILE @@FETCH_STATUS = 0

	BEGIN 
	PRINT @NOMBRE
	FETCH NEXT FROM CUR_NOMBRE INTO @NOMBRE
	END

DEALLOCATE CUR_NOMBRE
CLOSE CUR_NOMBRE


--STORE PROCEDURES
CREATE OR ALTER PROCEDURE PRO_CONSULTA
AS

	BEGIN
	SELECT *FROM EMPLEADOS
	END

EXEC PRO_CONSULTA;

--TRIGGERS O DISPARADORES
--INVESTIGAR MERGE INTO
--PARTITION BY
SELECT NOMBRE, APELLIDO, APODO, MAX(SUELDO) OVER (PARTITION BY SUELDO) AS WINDOWS_RESOULT
FROM EMPLEADOS

SELECT NOMBRE, APELLIDO, BONOS,  AVG(AFP) OVER (PARTITION BY BONOS ORDER BY BONOS DESC) AS RESULT
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO


SELECT APELLIDO, APODO, AVG(SUELDO) OVER (PARTITION BY SUELDO ) AS AVG_SUELDO
FROM EMPLEADOS


--WITH AS
WITH CTE_PRUEBA
AS (
	SELECT NOMBRE, APELLIDO, DEPARTAMENTO, BONOS, ARS
	FROM EMPLEADOS E
	JOIN NOMINA N ON E. CODIGO_EMPLEADO = N.CODIGO
	)

SELECT * FROM CTE_PRUEBA
-----------------------WITH AS CTE-------
WITH CTE_PRUEBA2
AS
	(
		SELECT CODIGO_EMPLEADO, NOMBRE, APELLIDO, BONOS, AFP, MAX(ARS)
		OVER (PARTITION BY ARS ) AS CTE_RESULT
		FROM EMPLEADOS E
		JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
	)

SELECT * FROM CTE_PRUEBA2;

--TEMPORARY TABLAS
CREATE TABLE #JUAN1

--SUB-CONSULTAS
---CUALES EMPLEADOS GANAN MAS O IGUAL AL SALARIO PROMEDIO

SELECT CODIGO_EMPLEADO, NOMBRE, APELLIDO,SUELDO
FROM EMPLEADOS WHERE SUELDO >=
				(SELECT AVG(SUELDO) AS SUELDO_PROMEDIO
				FROM EMPLEADOS)


SELECT NOMBRE, APELLIDO
FROM EMPLEADOS WHERE SUELDO <=
							(SELECT MIN(SUELDO) AS MIN_SUELDO
							FROM EMPLEADOS)


SELECT NOMBRE, APELLIDO, SUELDO
FROM EMPLEADOS WHERE NOMBRE IN
								(SELECT NOMBRE 
								FROM EMPLEADOS WHERE NOMBRE LIKE 'J%')


SELECT NOMBRE, APELLIDO, SUELDO, AFP
FROM EMPLEADOS E 
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
									WHERE SUELDO >=
									(SELECT MIN(SUELDO) AS SUMA_SUELDO FROM EMPLEADOS)

--PARTITION BY


SELECT * FROM EMPLEADOS;
SELECT * FROM Nomina