--PRACTICAS PARA ENTREVISTAS

--JOIN
--CLAUSULA GROUP BY
--CLAUSULA WHERE
--CLAUSULA HAVING
--IF - ELSE
--CASE
--FUNCIONES ESCALARES
--CURSOR
--STORE PROCEDURES
--TRIGGERS O DISPARADORES
--INVESTIGAR MERGE INTO
--PARTITION BY
--WITH AS
--TEMPORARY TABLAS
--SUB-CONSULTAS
--PARTITION BY

SELECT * FROM EMPLEADOS;
SELECT * FROM Nomina

--PRUEBA PARA VERIFICAR LAS CLAUSULAS GROUP BY AND HAVING

SELECT MAX(CODIGO_EMPLEADO) AS RESULTADO, NOMBRE,APELLIDO
FROM EMPLEADOS
GROUP BY NOMBRE, APELLIDO
HAVING MAX(Codigo_Empleado)  = 1008;
--------------------------------------------------------


---REALIZANDO RIGHT JOIN
SELECT NOMBRE, APELLIDO, BONOS, ARS
FROM  EMPLEADOS E
RIGHT JOIN NOMINA N ON E.Codigo_Empleado = N.CODIGO 


---REALIZANDO LEFT JOIN
SELECT NOMBRE, APELLIDO, BONOS, ARS
FROM NOMINA N
LEFT JOIN EMPLEADOS E ON E.Codigo_Empleado = N.CODIGO 

---REALIZANDO FULL OUTER JOIN
SELECT NOMBRE, APELLIDO, BONOS, ARS
FROM NOMINA N
FULL OUTER JOIN EMPLEADOS E ON E.Codigo_Empleado = N.CODIGO 

--REALIZANDO INNER JOIN
SELECT NOMBRE, APELLIDO, BONOS, ARS
FROM NOMINA N
INNER JOIN EMPLEADOS E ON E.Codigo_Empleado = N.CODIGO 


----CLAUSULA GROUP BY

SELECT CODIGO_EMPLEADO, NOMBRE, APELLIDO, MAX(SUELDO)  AS 'CONTANDO EL SUELDO'
FROM  Empleados 
GROUP BY Codigo_Empleado, NOMBRE, APELLIDO
HAVING MAX(SUELDO)>83000;

----CLAUSULA IF EXISTS

IF EXISTS (SELECT * FROM EMPLEADOS WHERE DEPARTAMENTO = 'IT')
(SELECT NOMBRE, SUELDO, APODO FROM EMPLEADOS WHERE DEPARTAMENTO ='IT')

ELSE
	SELECT 'NO HAY REGISTROS';

-----CASE

SELECT NOMBRE, SUELDO, APODO,
	CASE
	WHEN NOMBRE ='JUAN SORRILLA' AND SUELDO >= 75000 AND APODO = 'EL RONQUISTA' THEN 'AYUDA A TU ESPOSA'
	WHEN NOMBRE = 'JUAN ANTONIO' AND SUELDO = 80000 AND APODO = 'XIAOMI' THEN 'USTED COBRA MUY BIEN '
	WHEN NOMBRE = 'JUAN PEPEN' AND SUELDO >= 85000 AND APODO = 'GOGA' THEN 'FELICITACIONES'
	WHEN NOMBRE = 'LORENZO GUZMAN' AND SUELDO = 75000 AND APODO = 'LA COCA' THEN 'MARICA'
END AS COMENTARIO
FROM EMPLEADOS
ORDER BY SUELDO;

-----CREANDO CURSOR PARA VER LOS SALARIOS

DECLARE @VERSALARIOS INT
DECLARE C_VERSAL CURSOR FOR SELECT SUELDO FROM EMPLEADOS

OPEN C_VERSAL
FETCH NEXT FROM C_VERSAL INTO @VERSALARIOS
WHILE @@FETCH_STATUS = 0

BEGIN
	PRINT @VERSALARIOS
	FETCH NEXT FROM C_VERSAL INTO @VERSALARIOS
END

CLOSE C_VERSAL
DEALLOCATE C_VERSAL

----CREANDO OTRO CURSOR PARA VER

DECLARE @COL9 VARCHAR (35)
DECLARE CUR_NAME CURSOR FOR SELECT NOMBRE FROM EMPLEADOS

OPEN CUR_NAME 
FETCH NEXT FROM CUR_NAME INTO @COL9
WHILE @@FETCH_STATUS = 0

BEGIN
	PRINT @COL9
	FETCH NEXT FROM CUR_NAME INTO @COL9
END;

CLOSE CUR_NAME
DEALLOCATE CUR_NAME

-------CREANDO ESTORE PROCEDURE PARA INSERTAR DATOS

CREATE OR ALTER PROCEDURE PRO_INSERT
@COD INT,
@NOM VARCHAR (25),
@APELL VARCHAR (25),
@SUEL NUMERIC(25),
@APD VARCHAR(25),
@DEPA VARCHAR (25)
AS 
	BEGIN

	INSERT INTO EMPLEADOS VALUES (@COD, @NOM,@APELL,@SUEL, @APD , @DEPA)
	END

	EXEC PRO_INSERT 1030, 'KATHERINE', 'PEREZ',86000, 'LA ESPOSA','NOMINA'

---CREANDO PROCEDURE EN NOMINAS

CREATE OR ALTER PROCEDURE PRO_INSERT
@CODIGO INT,
@BONOS INT,
@AFP DECIMAL(10,2),
@ARS DECIMAL (10,2),
@ISR DECIMAL (10,2),
@SUB DECIMAL(10,2)
AS
	BEGIN
		INSERT INTO NOMINA  VALUES (@CODIGO,@BONOS, @AFP, @ARS,@ISR,@SUB)
	END;

EXEC PRO_INSERT 1044,2000,830.23,358.66,4500.52,785.36

SELECT * FROM NOMINA
--------SUBCONSULTAS ---

SELECT * FROM EMPLEADOS
SELECT* FROM NOMINA

SELECT NOMBRE, APELLIDO, SUELDO
FROM Empleados E
WHERE EXISTS (SELECT* FROM NOMINA N
			WHERE N.CODIGO = E.CODIGO_EMPLEADO
			AND SUBSIDIO = 125);

--------EMPLEADOS QUE GANAN MAS O IGUAL AL SALARIO PROMEDIO--
SELECT NOMBRE, APELLIDO, SUELDO
FROM Empleados WHERE SUELDO >=
							(SELECT AVG(SUELDO)
							FROM EMPLEADOS);
-------BUSCAR TODOS LOS NOMBRES DE CLIENTE CON DEPARTAMENTO IT

SELECT NOMBRE, APELLIDO
FROM EMPLEADOS 
WHERE CODIGO_EMPLEADO IN
					(SELECT CODIGO_EMPLEADO FROM EMPLEADOS
					WHERE DEPARTAMENTO = 'IT')


----TRIGGERS
CREATE OR ALTER TRIGGER TRI_INSERT
ON 
AS
BEGIN
END

----------------------------ROW NUMBER-----------------

USE DiplomadoSQL

SELECT * FROM CLIENTES;

SELECT NOMBRE, APELLIDO, TIPO_CLIENTE, ROW_NUMBER() OVER (PARTITION BY TIPO_CLIENTE
ORDER BY TIPO_CLIENTE) AS CONTEO
FROM CLIENTES


ROW_NUMBER() OVER (ORDER BY COMPANY_ID ASC)
FROM COMPANY;

---------------------------WITH ---CTES

WITH PRUEBA2_CTE AS (
		SELECT NOMBRE, APELLIDO, EMAIL
		FROM CLIENTES
)

SELECT APELLIDO, EMAIL FROM PRUEBA2_CTE

---------------REALIZANDO VARIAS CONSULTAS DE CTEs----------------
SELECT * FROM ALQUILER

WITH CTE_PRUEBA3
AS
	(
	SELECT ID_PELICULA, ENTRADAS_VENDIDAS, CAPACIDAD_PERSONAS
	FROM ALQUILER
	)
	
SELECT ID_PELICULA, AVG(ENTRADAS_VENDIDAS) AS AVERAGE_ENTRADAS
FROM CTE_PRUEBA3
GROUP BY ID_PELICULA, CAPACIDAD_PERSONAS;

---------CREANDO OTRA CTE-----

	WITH CTE_EMPLEADO_CINE 
	AS (
		SELECT NOMBRE_EMPLEADO, APELLIDO, PUESTO
		FROM EMPLEADO
		WHERE ESTATUS = '1'
		)
	
SELECT APELLIDO, PUESTO
FROM CTE_EMPLEADO_CINE;


	SELECT A.ID_ALQUILER, COUNT(A.ENTRADAS_VENDIDAS), E.NOMBRE_EMPLEADO
FROM EMPLEADO E
LEFT JOIN ALQUILER A ON 

-------------------------------------.
--PRACTICAS PARA ENTREVISTAS

SELECT * FROM EMPLEADOS
SELECT * FROM NOMINA

--JOIN--(LEFT, RIGHT, FULL, INNER)
SELECT NOMBRE, APELLIDO, SUELDO, BONOS, AFP, ISR
FROM EMPLEADOS E
INNER JOIN NOMINA N ON E.Codigo_Empleado = N.CODIGO 

SELECT NOMBRE, APELLIDO, SUELDO, BONOS, AFP, ISR
FROM EMPLEADOS E
RIGHT JOIN NOMINA N ON E.Codigo_Empleado = N.CODIGO

SELECT NOMBRE, APELLIDO, SUELDO, BONOS, AFP, ISR
FROM  NOMINA N
LEFT JOIN EMPLEADOS E ON E.Codigo_Empleado = N.CODIGO

SELECT NOMBRE, APELLIDO, SUELDO, BONOS, AFP, ISR
FROM  NOMINA N
FULL OUTER JOIN EMPLEADOS E ON E.Codigo_Empleado = N.CODIGO

--CLAUSULA GROUP BY
SELECT NOMBRE, APELLIDO, AVG(BONOS) AS AVERAGE_BONOS
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY NOMBRE, APELLIDO

--CLAUSULA WHERE
SELECT NOMBRE, APELLIDO, BONOS, AFP
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
WHERE NOMBRE IN ('SORILLA','JUAN ANTONIO','JUAN MEJIA','JUAN LA LUZ')

SELECT NOMBRE, APELLIDO, BONOS, AFP
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
WHERE NOMBRE = 'JUAN ANTONIO' 

--CLAUSULA HAVING
SELECT NOMBRE, APELLIDO, MAX(SUELDO) AS SUELDO_MAXIMO
FROM EMPLEADOS E 
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY NOMBRE, APELLIDO
HAVING MAX(SUELDO)>75000
ORDER BY 1,2 DESC;

SELECT NOMBRE, APELLIDO, MIN(AFP) AS MINIMO_AFP ,MAX(ARS) AS MAX_ARS
FROM EMPLEADOS E
LEFT JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
GROUP BY NOMBRE, APELLIDO
HAVING MIN(AFP)<= 698.85 AND MAX(ARS)>=287.63

--IF - ELSE
IF EXISTS (SELECT * FROM EMPLEADOS WHERE DEPARTAMENTO = 'ADM')
	(SELECT NOMBRE, APELLIDO, APODO, AFP 
	FROM EMPLEADOS E
	JOIN NOMINA N on E.CODIGO_EMPLEADO = N.CODIGO
	WHERE DEPARTAMENTO = 'ADM')
ELSE
	SELECT 'NO HAY REGISTROS DISPONIBLES' AS RESULTADO;
----------------------------------------------------------------
IF EXISTS (SELECT * FROM NOMINA WHERE AFP = 387.85 )
	(SELECT BONOS, AFP, ARS  FROM NOMINA WHERE AFP = 387.85)
ELSE
	SELECT 'NO HAY REGISTRO ' AS RESULTADO

--------
SELECT * FROM EMPLEADOS
SELECT * FROM NOMINA

--CASE
	SELECT NOMBRE, APELLIDO, SUELDO,
CASE
	 WHEN DEPARTAMENTO = 'ADM' AND SUELDO =75000 THEN 'ADMINISTRACION GRANDIOSA'
	 WHEN DEPARTAMENTO = 'INGENIERIA' THEN 'ING'
	 WHEN APELLIDO = 'LOPOLDO' THEN 'EL MAS BUSCADO'
	 WHEN NOMBRE = 'JUAN LA LUZ' THEN 'NO SE VA'
	 WHEN SUELDO <= 100000 THEN 'USTED NO COBRA MUY BUENO'
END AS RESULTADO
FROM EMPLEADOS
	

--FUNCIONES ESCALARES
--CURSOR
--STORE PROCEDURES
--TRIGGERS O DISPARADORES
--INVESTIGAR MERGE INTO
--PARTITION BY
--WITH AS
--CREATE VIEW
--TEMPORARY TABLAS

--PARTITION BY
SELECT NOMBRE, MAX(SUELDO) OVER (PARTITION BY SUELDO ) AS RESULTADO
FROM EMPLEADOS 

SELECT NOMBRE, APELLIDO, DEPARTAMENTO, MIN(SUELDO) OVER (PARTITION BY DEPARTAMENTO) AS MIN_SUELDO
FROM EMPLEADOS

--SUB-CONSULTAS
SELECT * FROM EMPLEADOS
SELECT * FROM NOMINA

--SUBCONSULTA EN EL SELECT
SELECT NOMBRE, APELLIDO, (SELECT AVG(SUELDO) FROM EMPLEADOS)AS SUELDO_PROMEDIO
FROM EMPLEADOS

--SUBCONSULTA EN EL WHERE
SELECT NOMBRE, APELLIDO, AFP
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
WHERE SUELDO IN (SELECT SUELDO = 75000 FROM EMPLEADOS)

SELECT NOMBRE, APELLIDO, APODO, ARS
FROM EMPLEADOS E
JOIN NOMINA N ON E.CODIGO_EMPLEADO = N.CODIGO
WHERE AFP IN (SELECT AFP FROM EMPLEADOS )

--Escribe una consulta que encuentre los empleados con salarios superiores al salario promedio de su departamento.

SELECT NOMBRE, SUELDO
FROM EMPLEADOS E
WHERE SUELDO >
	(SELECT AVG(SUELDO) FROM EMPLEADOS E2
	WHERE E.DEPARTAMENTO = E2.DEPARTAMENTO)

--Escribe una consulta que devuelva el segundo salario más alto en la tabla de empleados.
SELECT SUELDO,  MAX(SUELDO) AS MAX_SALARY
FROM EMPLEADOS 
WHERE SUELDO < (SELECT MAX(SUELDO) FROM EMPLEADOS)
GROUP BY SUELDO
ORDER BY 1,2

--Escribe una consulta para contar el número de empleados en cada departamento.
SELECT DEPARTAMENTO, COUNT(*) AS CONTEO_DEPARTAMENTO
FROM EMPLEADOS
GROUP BY DEPARTAMENTO

