---PROCEDIMIENTOS ALMACENADOS CON PARAMETROS DE ENTRADA

USE DiplomadoSQL
SELECT * FROM EMPLEADOS

CREATE OR ALTER PROCEDURE P_PARAMETROS_ENTRADA
	@NOMBRE VARCHAR(25) = 'JUAN ANTONIO',
	@DEPARTAMENTO VARCHAR(25) = 'INGENIERIA'
AS
	BEGIN
		SELECT * FROM EMPLEADOS WHERE NOMBRE = @NOMBRE AND DEPARTAMENTO = @DEPARTAMENTO
	END
EXEC P_PARAMETROS_ENTRADA

-----PROCEDIMIENTOS CON PARAMETROS DE SALIDA

CREATE OR ALTER PROCEDURE P_PARAMETROS_SALIDA
	@DEPARTAMENTO VARCHAR(25) = '%',
	@SUMA NUMERIC (18,0) OUTPUT,
	@PROMEDIO NUMERIC (18,0) OUTPUT

AS
	SELECT * FROM EMPLEADOS WHERE DEPARTAMENTO LIKE @DEPARTAMENTO
	SELECT @SUMA = SUM(SUELDO) FROM EMPLEADOS WHERE  DEPARTAMENTO = @DEPARTAMENTO
	SELECT @PROMEDIO = AVG(SUELDO) FROM EMPLEADOS WHERE DEPARTAMENTO = @DEPARTAMENTO;

DECLARE
	@SUMATORIA NUMERIC (18,0), @PROM NUMERIC (18,0)
	EXEC P_PARAMETROS_SALIDA 'IT', @SUMATORIA OUTPUT, @PROM OUTPUT
	SELECT @SUMATORIA AS TOTAL , @PROM AS PROMEDIO_GERNERAL;

--INSERTANDO DATOS EN LA TABLA PARA LA CONFIRMACION DEL PROCESO

INSERT INTO EMPLEADOS VALUES (1007,'JUAN PEPEN','SARAGOGA',85000,'GOGA','IT')
INSERT INTO EMPLEADOS VALUES (1008,'JUAN AZUL','PLANETARIO',80000,'AZUL','INGENIERIA')
INSERT INTO EMPLEADOS VALUES (1009,'LORENZO GUZMAN','CALIENTE',75000,'LA COCA','OPERACIONES')

SELECT * FROM NOMINA

INSERT INTO NOMINA VALUES (1007, 900,451.56,352.66,652.25,1500.23)
INSERT INTO NOMINA VALUES (1008, 152,896.56,789.66,123.25,7852.23)
INSERT INTO NOMINA VALUES (1009, 368,698.56,456.66,652.25,4563.23)

