--REALIZANDO CONSULTAS CON STORE PROCEDURES

CREATE  OR ALTER PROCEDURE P_CONSULTAR
AS
	BEGIN
		SELECT * FROM EMPLEADOS
	END
EXEC P_CONSULTAR






---INSERTANDO DATOS A MI TABLA EMPLEADOS CRUD

CREATE OR ALTER PROCEDURE P_INSERTAR_DATOS
@CODIGO_EMPLEADO INT,
@NOMBRE VARCHAR(25),
@APELLIDO VARCHAR(25),
@SUELDO NUMERIC(18,0),
@APODO VARCHAR(25),
@DEPARTAMENTO VARCHAR(25)

AS
	BEGIN
		INSERT INTO EMPLEADOS VALUES (@CODIGO_EMPLEADO,@NOMBRE,@APELLIDO,@SUELDO,@APODO,@DEPARTAMENTO)
	END

---CON ESTA INSTRUCCION SE INSERTANDO LOS PARAMETROS
EXEC P_INSERTAR_DATOS 1007,'LUPITA','VENEGAS',56800,'LA CURA','MANTENIMIENTO'

SELECT * FROM EMPLEADOS

SP_HELP EMPLEADOS

---UPDATING DATOS CON STORE PROCEDURE

CREATE OR ALTER PROCEDURE PRO_UPDATE
@CODIGO_EMPLEADO INT,
@NOMBRE VARCHAR(25),
@APELLIDO VARCHAR(25),
@SUELDO NUMERIC(18,0),
@APODO VARCHAR(25),
@DEPARTAMENTO VARCHAR(25)
AS
	BEGIN
		UPDATE EMPLEADOS SET NOMBRE = @NOMBRE, APELLIDO = @APELLIDO, SUELDO = @SUELDO, APODO = @APODO, DEPARTAMENTO = @DEPARTAMENTO
		WHERE CODIGO_EMPLEADO = @CODIGO_EMPLEADO
	END

EXEC PRO_UPDATE 1001,'JUAN ALFONSO','PEGUERO',25000,'MACOTICA INCOMODA','IT'

SELECT * FROM EMPLEADOS

------DELITING DATOS CON STORE PROCEDURE
CREATE OR ALTER PROC P_DELETE_PROC
@CODIGO_EMPLEADO INT
AS
	BEGIN
		DELETE EMPLEADOS 
		WHERE CODIGO_EMPLEADO = @CODIGO_EMPLEADO 
	END
EXEC P_DELETE_PROC 1001

