--SUBCONSULTAS

SELECT * FROM EMPLEADOS

---EMPLEADOS QUE SU SUELDO ES MAYOR O IGUAL AL SALARIO PROMEDIO.
SELECT NOMBRE, APELLIDO, SUELDO
FROM EMPLEADOS 
WHERE SUELDO > = 
			( SELECT AVG(SUELDO)
			FROM EMPLEADOS);

-------------------------------
SELECT * FROM Compras_Bikes


SELECT [MARITAL STATUS],[GENDER],[CHILDREN]
FROM Compras_Bikes 
WHERE [Children] >1
			(SELECT COUNT([CHILDREN])
			FROM Compras_Bikes);


SELECT [Occupation],[HOME OWNER],[CARS]
FROM Compras_Bikes
WHERE [MARITAL STATUS] IN
	(SELECT [MARITAL STATUS]
	FROM Compras_Bikes
	WHERE [REGION]= 'Europe')

