--TRIGGERS

USE DIPLOMADOSQL

CREATE TABLE CONTROL (
USUARIO VARCHAR(30),
FECHA DATE,
ACCION VARCHAR (10)
);

CREATE TABLE PRUEBA (
NOMBRE VARCHAR(15),
APELLIDO VARCHAR (15),
SUELDO INT
);

CREATE OR ALTER TRIGGER TRI_INSERT
ON PRUEBA
AFTER INSERT
AS 
	BEGIN
		DECLARE @USUARIO VARCHAR(20);
		SET @USUARIO = SUSER_NAME();
		INSERT INTO CONTROL VALUES (@USUARIO, GETDATE(),'INSERT')
	END;

INSERT INTO PRUEBA VALUES ('LUIS','PEREZ',65000)

SELECT * FROM CONTROL

---TRIGGER PARA UPDATE REGISTROS

CREATE OR ALTER TRIGGER TRI_UPDATE
ON PRUEBA
AFTER UPDATE
AS 
	BEGIN
		DECLARE @USUARIO VARCHAR(20);
		SET @USUARIO = SUSER_NAME();
		INSERT INTO CONTROL VALUES (@USUARIO, GETDATE(),'UPDATE')
	END;

INSERT INTO PRUEBA VALUES ('LUIS','PEREZ',65000)
UPDATE PRUEBA SET NOMBRE = 'FRANCISCO' WHERE NOMBRE = 'LUIS';

SELECT * FROM CONTROL
SELECT * FROM PRUEBA		

